# main config for srs.
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

vhost __defaultVhost__ {
    enabled         on;

    chunk_size      4096;

    # Enables publishing to /live/
    stream {
        enabled on;
    }
}
