# main config for srs.
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

vhost __defaultVhost__ {
    enabled         on;

    chunk_size      4096;

    # Accept incoming RTMP stream at /live/*
    stream {
        enabled on;
    }

    # Optional: Enable HTTP API (optional)
    http_api {
        enabled     on;
        listen      1985;
    }

    # Optional: HTTP server (used by some tools)
    http_server {
        enabled     on;
        listen      8080;
        dir         ./objs/nginx/html;
    }

    # Optional: Keep GoPro from dropping connection
    tcp_nodelay     on;
}
